name: Visit google


# run the job at a scheduled time
on:
  push:
    branches: main


jobs:
  fetch-from-API:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R package linux dependencies
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libudunits2-dev libgdal-dev


        # source: https://gist.github.com/julionc/7476620
      - name: Install phantomjs and its dependencies
        run: |
          sudo apt-get install build-essential chrpath libssl-dev libxft-dev
          sudo apt-get install libfreetype6 libfreetype6-dev
          sudo apt-get install libfontconfig1 libfontconfig1-dev
          cd ~
          export PHANTOM_JS="phantomjs-1.9.8-linux-x86_64"
          wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
          sudo tar xvjf $PHANTOM_JS.tar.bz2
          sudo mv $PHANTOM_JS /usr/local/share
          sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
          phantomjs --version

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run R script

        # This line is the only different one!
        run: Rscript -e 'source("visit_google.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . 
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
